### ISSUE TITLE
ARK Epic Games Version

### ISSUE THREAD

**Issue by johngriffin1** [Coder-256/UnrealGPUPatcher#3]
ARK: Survival Evolved is currently free on the epic games store and I was wondering if this patcher works on that version too. Thanks!

**Comment by jacob-greenfield** [comment]
I haven't tested it but I imagine it should work! Feel free to try it, and let me know how it goes.

**Comment by johngriffin1** [comment]
I just looked and it seems that the Epic Games Version is Windows only though.

**Comment by jacob-greenfield** [comment]
Ok, this patcher is meant to patch games built with Unreal Engine for macOS to work on Apple Silicon GPUs. It is not necessary for Windows games. Hope this helps.

**Comment by johngriffin1** [comment]
Ok, thank you. That is what I thought.
